openapi: 3.0.1
info:
  title: CB - Card Catalog Manager
  description: 'Administration Portal card catalog management api'
  version: 1.0.0
servers:
  - url: https://api-dev.plataformacb.com
paths:
  /crm/v1/custom-card/cards/{id}:
    put:
      tags:
        - Card
      summary: Change card status by ID
      operationId: updateCardStatus
      parameters:
        - in: header
          name: x-channel-key
          schema:
            type: string
          required: true
          description: Channel Key
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Card ID
        - in: query
          name: active
          schema:
            type: boolean
          required: true
          description: New card status
      security:
        - CRMAuth: [ ]
      responses:
        '200':
          description: Card status changed
        '404':
          description: "Card with given id is not found."
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: "Error on this microservice or in communication with another microservice"
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorMessage'
  /crm/v1/custom-card/cards:
    get:
      tags:
        - Card
      summary: Get card catalog
      operationId: getCustomCards
      parameters:
        - in: header
          name: x-channel-key
          schema:
            type: string
          required: true
          description: Channel Key
      security:
        - CRMAuth: [ ]
      responses:
        '200':
          description: Cards list
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/cardCatalogResponse'
        '404':
          description: "No cards found."
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: "Error on this microservice or in communication with another microservice"
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ErrorMessage'
    post:
      tags:
        - Card
      summary: Create a new Card
      operationId: createNewCard
      parameters:
        - in: header
          name: x-channel-key
          schema:
            type: string
            nullable: false
          required: true
          allowEmptyValue: false
          description: Channel Key
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              $ref: '#/components/schemas/newCardRequest'
            encoding:
              image:
                contentType: image/png
      responses:
        '201':
          description: New card created
          headers:
            location:
              schema:
                type: string
              description: New Card URI
        '400':
          description: Empty or invalid fields
        '500':
          description: Card can't be saved
components:
  schemas:
    cardCatalogResponse:
      properties:
        SETUP:
          type: array
          items:
            $ref: '#/components/schemas/card'
    card:
      type: object
      properties:
        id:
          type: string
          description: card id
        code:
          type: string
          description: card design code
        name:
          type: string
          description: card name
        price:
          type: number
          description: card price
        roles:
          type: array
          items:
            type: string
          description: card roles
        createdAt:
          type: string
          description: creation date
        updatedAt:
          type: string
          description: update date
        status:
          type: boolean
          description: card status
      example:
        id: "080987ef-5de5-4f52-bd4f-cc2d8c3619bb-2"
        code: "001"
        name: "Minions"
        price: 22.12
        roles:
          - credicard
          - beta
        createdAt: "2020-12-10T12:24:24.361"
        updatedAt: "2020-12-10T12:24:24.361"
        status: true
    newCardRequest:
      type: object
      properties:
        card:
          type: object
          required:
            - cardId
            - company
            - name
            - accessible
            - price
            - active
            - available
            - flow
          properties:
            cardId:
              type: string
              description: card design code
              minLength: 3
              maxLength: 3
            company:
              type: string
              description: Partner company
            name:
              type: string
              description: Card name
              minLength: 1
              maxLength: 24
              nullable: false
            description:
              type: string
              description: Card description
              minLength: 1
              maxLength: 120
              nullable: false
            accessible:
              type: string
              description: Card image description
              minLength: 1
              maxLength: 400
              nullable: false
            price:
              type: number
              format: double
              description: Card price
              example: 22.22
            active:
              type: boolean
              description: Card status
            available:
              type: boolean
              description: Card avaibility
              default: true
            flow:
              description: Card setup flow
              type: array
              items:
                type: string
              example:
                - SETUP
                - DUPLICATE
              nullable: false
            roles:
              description: User roles
              type: array
              items:
                type: string
              example:
                - credicard
                - beta
        image:
          type: string
          format: binary
    ErrorMessage:
      required:
        - type
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    CRMAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: CRM Authentication